name: Docker Hub

on:
  push:
    branches:
    - develop
    tags:
    - "v*"

concurrency:
  group: ci-${{ github.repository }}-dockerhub

jobs:
  develop-docker:
    if: github.repository_owner == 'jakobandersen' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: jakobandersen
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: jakobandersen/githubTest:develop
  release-docker:
    if: github.repository_owner == 'jakobandersen' && startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: jakobandersen
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: jakobandersen/githubTest:${{github.ref_name}}
